### ISSUE TITLE
[UI/UX] Imporvement for Shopping Cart Button

### ISSUE THREAD

**Issue by etherio97** [minkhant1999/aquatic-plants#1]
---
name: 🚀 Feature Request
about: Imporvement for Shopping Cart Button
labels: Feature
---

**Description**

Shopping cart button as shown in figure should display the number of items in cart for more interactive.

<img width="497" alt="Screen Shot 2021-11-15 at 7 03 37 PM" src="https://user-images.githubusercontent.com/50423290/141783014-857d824f-af6f-453b-8c2c-4d0291a697aa.png">

**Example**

<img width="323" alt="Screen Shot 2021-11-15 at 7 03 48 PM" src="https://user-images.githubusercontent.com/50423290/141783740-969908c2-824a-4853-b156-be9e08320682.png">

## Reference

- [Badge | Angular Material](https://material.angular.io/components/badge/overview)

**Comment by minkhant1999** [comment]
Done
