### ISSUE TITLE
[UI/UX] Order Confirm Page

### ISSUE THREAD

**Issue by etherio97** [minkhant1999/aquatic-plants#2]
---
name: 🚀 Feature Request
about: Order Confirm Page
labels: Feature
---

**Description**

When an order is submitted, there should be display order success with `order id` or `reference id`.

<img width="1175" alt="Screen Shot 2021-11-15 at 7 18 18 PM" src="https://user-images.githubusercontent.com/50423290/141785073-4c7ecb2e-6a93-4589-a452-e4cc848589fc.png">

**Example**

![CZN8XLyWIAE8iMg](https://user-images.githubusercontent.com/50423290/141784907-8ffe5ed0-f7eb-421e-b115-f0c95bfceb46.png)

**Comment by minkhant1999** [comment]
Done: with snackbar
