### ISSUE TITLE
[BUG] Multiple order submission

### ISSUE THREAD

**Issue by etherio97** [minkhant1999/aquatic-plants#3]
---
name: 🐛 Bug Report
about: ⚠️ Multiple order submission
labels: Bug
---

**Description**

Currenlty mutiple click on order form will be trigger mutiple submission for same order. This accident might be quite often for poor network connection.

<img width="1680" alt="Screen Shot 2021-11-15 at 7 30 56 PM" src="https://user-images.githubusercontent.com/50423290/141786676-66feed4f-e0f5-4c2a-bdbb-a99dfd1dbd72.png">

**Example**

<img width="204" alt="Screen Shot 2021-11-15 at 7 39 11 PM" src="https://user-images.githubusercontent.com/50423290/141787393-6e969dbf-deb8-4201-9c2e-256faa2f7838.png">

**Comment by minkhant1999** [comment]
Fixed ...
